<script>
  import Answers from "./Answers.svelte";
  let count = 0;
  const answers = {
    A: {
      1: "sos, ser",
      2: "sos, ser, szynka",
      3: "sos, ser, pepperoni, pieczarki, cebula",
      4: "sos,ser, szynka, kukurydza",
      5: "sos,ser, boczek, cebula, pieczarki",
      6: "sos,ser, boczek",
      7: "sos,ser, boczek, wieprzowina, sos majonezowy",
      8: "sos,ser, pieczarki",
      9: "sos,ser, cebula, kukurydza, papryczki, pomidorki",
      10: "sos,ser, pepperoni, cebula, kukurydza",
      11: "sos,ser, pepperoni, szynka, boczek, pieczarki",
      12: "sos,ser, boczek, pepproni",
      13: "sos,ser, cebula, cebula",
      14: "sos,ser, pieczony kurczak, cebula, kukurydza",
      15: "sos,ser, pepperoni, szynka, cebula, pieczarki, boczek, wieprzowina",
      16: "sos,ser, szpinak, cebula, pieczarki, pomidorki, oliwki",
      17: "sos,ser, boczek, pieczarki, papryczki, pieczony kurczak",
      18: "sos,mix serowy, ser plesniowy",
      19: "sos,ser, szynka wloska, ser feta, rukola",
      20: "sos,ser, papryczki, pieczony kurczak, ser plesniowy, rukola",
      21: "sos,ser, pepperoni, szynka, cebula, pieczarki, wolowina, wieprzowina, oliwki, papryczki, extra ser",
      22: "sos,ser, ser corregio, gruszka, szpinak, slonecznik & dynia",
    },
    B: {
      1: "sam sos",
      2: "sos, ser, szpinak",
      3: "sos, ser, szynka, pieczarki, cebula",
      4: "sos,ser, szynka, cebula",
      5: "sos,ser, kukurydza, cebula, pieczarki", 
      6: "sos,ser, szynka",
      7: "sos,ser, szynka, wolowina, sos majonezowy",
      8: "sos,ser, szynka, pieczarki",
      9: "sos,ser, cebula, kukurydza, jalapeno, pomidorki",
      10: "sos,ser, pepperoni, pieczarki, jalapeno",
      11: "sos,ser, pepperoni, szynka, wolowina, pieczarki",
      12: "sos,ser, boczek, wolowina",
      13: "sos,ser, cebula, wolowina",
      14: "sos,ser, pieczony kurczak, cebula, pieczarki",
      15: "sos,ser, pepperoni, boczek, cebula, pieczarki, wolowina, wieprzowina",
      16: "sos,ser, szpinak, cebula, pieczarki, pomidorki, oliwki, feta",
      17: "sos,ser, boczek, cebula, jalapeno, pieczony kurczak",
      18: "sos, ser, mix serowy, ser plesniowy",
      19: "sos,ser, szynka wloska, ser corregio, szpinak",
      20: "sos,ser, suszone pomidory, pieczony kurczak, ser corregio, rukola",
      21: "sos,ser, pepperoni, szynka, cebula, pieczarki, wolowina, wieprzowina, oliwki, papryczki",
      22: "sos,ser, ser feta, gruszka, szpinak, slonecznik & dynia",
    },
    C: {
      1: "sam ser",
      2: "sos, ser, tunczyk",
      3: "sos, ser, boczek, pieczarki, cebula",
      4: "sos,ser, szynka, ananas",
      5: "sos,ser, szynka, cebula, pieczarki",
      6: "sos,ser, pieczarki",
      7: "sos,ser, boczek, wolowina, sos majonezowy",
      8: "sos,ser, pepperoni, pieczarki",
      9: "sos,ser, pieczarki, kukurydza, papryczki, pomidorki",
      10: "sos,ser, szynka, cebula, jalapeno",
      11: "sos,ser, pepperoni, wolowina, wieprzowina, pieczarki",
      12: "sos,ser, boczek, wieprzowina",
      13: "sos,ser, cebula, kebab", 
      14: "sos,ser, kebab, cebula, kukurydza",
      15: "sos,ser, pepperoni, szynka, cebula, pieczarki, wieprzowina",
      16: "sos,ser, szynka, cebula, pieczarki, pomidorki, oliwki, feta",
      17: "sos,ser, szynka, cebula, papryczki, pieczony kurczak",
      18: "sos, mix serowy, ser plesniowy, feta",
      19: "sos,ser, szynka wloska, ser corregio, rukola",
      20: "sos,ser, suszone pomidory, pieczony kurczak, ser plesniowy, rukola",
      21: "sos,ser, pepperoni, boczek, cebula, pieczarki, wolowina, wieprzowina, oliwki, jalapeno, extra ser",
      22: "sos,ser, ser kozi, gruszka, szpinak, slonecznik",
    },
    D: {
      1: "za trudne",
      2: "sos, ser, pepperoni",
      3: "sos, ser, kukurydza, pieczarki, cebula",
      4: "sos,ser, szynka, pieczarki",
      5: "sos,ser, pepperoni, cebula, pieczarki",
      6: "sos,ser, papryczki",
      7: "sos,ser, boczek, wolowina",
      8: "sos,ser, boczek, pieczarki",
      9: "sos,ser, cebula, pieczarki, papryczki, szpinak",
      10: "sos,ser, pepperoni, cebula, jalapeno",
      11: "sos,ser, pepperoni, szynka, boczek, pomidorki",
      12: "sos,ser, boczek, pieczarki",
      13: "sos,ser, cebula, pieczony kurczak",
      14: "sos,ser, pieczony kurczak, pomidorki, kukurydza",
      15: "sos,ser, pepperoni, szynka, cebula, pieczarki, wolowina, wieprzowina",
      16: "sos,ser, szpinak, cebula, pieczarki, papryczki, oliwki, feta",
      17: "sos,ser, boczek, cebula, papryczki, pieczony kurczak",
      18: "sos, mix serowy, ser plesniowy, ser kozi",
      19: "sos,ser, szynka, ser corregio, rukola",
      20: "sos,ser, pomidorki, pieczony kurczak, ser feta, rukola",
      21: "sos,ser, pepperoni, szynka, cebula, pomidorki, wolowina, wieprzowina, oliwki, papryczki, extra ser",
      22: "sos,ser, ser kozi, gruszka, szpinak, slonecznik & dynia",
    },
  };


</script>

<main>
  <Answers {answers} {count} />
</main>

<style>
</style>
